version: '3.9'
services:
  playwright-tests:
    build: .
    env_file:
      - .env
    volumes:
      - ./playwright-report:/wikipedia-test-task/playwright-report
    entrypoint: ["npx", "playwright", "test", "--reporter=html"]
